-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS bookings.products
(
    product_id uuid NOT NULL DEFAULT gen_random_uuid(),
    brand_id uuid NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    weight numeric NOT NULL,
    count integer NOT NULL DEFAULT 0,
    price numeric NOT NULL DEFAULT 0,
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS bookings.brand
(
    brand_id uuid NOT NULL DEFAULT gen_random_uuid(),
    title character varying(255) NOT NULL,
    PRIMARY KEY (brand_id),
    UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS bookings.orders
(
    order_id uuid NOT NULL DEFAULT gen_random_uuid(),
    payment_status boolean NOT NULL DEFAULT false,
    delivery_status boolean NOT NULL DEFAULT false,
    delivery_address character varying(255),
    user_id uuid NOT NULL,
    PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS bookings.orders_products
(
    order_id uuid NOT NULL,
    product_id uuid NOT NULL,
    count integer NOT NULL DEFAULT 1,
    fix_price numeric NOT NULL DEFAULT 0,
    PRIMARY KEY (order_id, product_id)
);

CREATE TABLE IF NOT EXISTS bookings.categories
(
    category_id uuid NOT NULL DEFAULT gen_random_uuid(),
    title character varying(255) NOT NULL,
    parent_category_id uuid,
    PRIMARY KEY (category_id),
    UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS bookings.products_category
(
    product_id uuid NOT NULL,
    category_id uuid NOT NULL,
    PRIMARY KEY (product_id, category_id)
);

CREATE TABLE IF NOT EXISTS bookings.baskets
(
    basket_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    PRIMARY KEY (basket_id)
);

CREATE TABLE IF NOT EXISTS bookings.baskets_products
(
    basket_id uuid NOT NULL,
    product_id uuid NOT NULL,
    count integer NOT NULL DEFAULT 1,
    PRIMARY KEY (basket_id, product_id)
);

CREATE TABLE IF NOT EXISTS bookings.users
(
    user_id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    PRIMARY KEY (user_id),
    UNIQUE (email)
);

ALTER TABLE IF EXISTS bookings.products
    ADD FOREIGN KEY (brand_id)
    REFERENCES bookings.brand (brand_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.orders
    ADD FOREIGN KEY (user_id)
    REFERENCES bookings.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.orders_products
    ADD FOREIGN KEY (order_id)
    REFERENCES bookings.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.orders_products
    ADD FOREIGN KEY (product_id)
    REFERENCES bookings.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.categories
    ADD FOREIGN KEY (parent_category_id)
    REFERENCES bookings.categories (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.products_category
    ADD FOREIGN KEY (product_id)
    REFERENCES bookings.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.products_category
    ADD FOREIGN KEY (category_id)
    REFERENCES bookings.categories (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.baskets
    ADD FOREIGN KEY (user_id)
    REFERENCES bookings.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.baskets_products
    ADD FOREIGN KEY (basket_id)
    REFERENCES bookings.baskets (basket_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.baskets_products
    ADD FOREIGN KEY (product_id)
    REFERENCES bookings.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;