-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS bookings.products
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    brand_id uuid NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    weight numeric NOT NULL,
    category_id uuid,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings.brand
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    title character varying(255) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS bookings.orders
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    payment_status boolean NOT NULL DEFAULT false,
    delivery_status boolean NOT NULL DEFAULT false,
    delivery_address character varying(255),
    user_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings.orders_products
(
    order_id uuid NOT NULL,
    product_id uuid NOT NULL,
    count integer NOT NULL DEFAULT 1,
    fix_price numeric NOT NULL DEFAULT 0,
    PRIMARY KEY (order_id, product_id)
);

CREATE TABLE IF NOT EXISTS bookings.categories
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    title character varying(255) NOT NULL,
    parent_category_id uuid,
    PRIMARY KEY (id),
    UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS bookings.baskets
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings.baskets_products
(
    basket_id uuid NOT NULL,
    product_id uuid NOT NULL,
    count integer NOT NULL DEFAULT 1,
    PRIMARY KEY (basket_id, product_id)
);

CREATE TABLE IF NOT EXISTS bookings.users
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS bookings.shops
(
    id uuid DEFAULT gen_random_uuid(),
    title character varying(255) NOT NULL,
    address character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings.shjp_data
(
    product_id uuid NOT NULL,
    shop_id uuid NOT NULL,
    cost numeric NOT NULL DEFAULT 0,
    count integer NOT NULL DEFAULT 0,
    PRIMARY KEY (product_id, shop_id)
);

CREATE TABLE IF NOT EXISTS bookings.reviews
(
    user_id uuid NOT NULL,
    product_id uuid NOT NULL,
    text text,
    rating integer NOT NULL DEFAULT 0,
    date date NOT NULL DEFAULT NOW(),
    parent_review_id uuid,
    id uuid DEFAULT gen_random_uuid(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings.photos
(
    id uuid DEFAULT gen_random_uuid(),
    product_id uuid NOT NULL,
    photo bytea NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (photo)
);

CREATE TABLE IF NOT EXISTS bookings.parameters
(
    id uuid DEFAULT gen_random_uuid(),
    title character varying(255) NOT NULL,
    type character varying(32) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS bookings.parameters_values
(
    product_id uuid NOT NULL,
    parameter_id uuid NOT NULL,
    boolean_value boolean,
    string_value character varying(255),
    numeric_value numeric,
    PRIMARY KEY (parameter_id, product_id)
);

CREATE TABLE IF NOT EXISTS bookings.parameters_categories
(
    parameter_id uuid NOT NULL,
    category_id uuid NOT NULL
);

ALTER TABLE IF EXISTS bookings.products
    ADD FOREIGN KEY (brand_id)
    REFERENCES bookings.brand (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.products
    ADD FOREIGN KEY (category_id)
    REFERENCES bookings.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.orders
    ADD FOREIGN KEY (user_id)
    REFERENCES bookings.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.orders_products
    ADD FOREIGN KEY (order_id)
    REFERENCES bookings.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.orders_products
    ADD FOREIGN KEY (product_id)
    REFERENCES bookings.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.categories
    ADD FOREIGN KEY (parent_category_id)
    REFERENCES bookings.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.baskets
    ADD FOREIGN KEY (user_id)
    REFERENCES bookings.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.baskets_products
    ADD FOREIGN KEY (basket_id)
    REFERENCES bookings.baskets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.baskets_products
    ADD FOREIGN KEY (product_id)
    REFERENCES bookings.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.shjp_data
    ADD FOREIGN KEY (product_id)
    REFERENCES bookings.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.shjp_data
    ADD FOREIGN KEY (shop_id)
    REFERENCES bookings.shops (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.reviews
    ADD FOREIGN KEY (user_id)
    REFERENCES bookings.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.reviews
    ADD FOREIGN KEY (product_id)
    REFERENCES bookings.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.reviews
    ADD FOREIGN KEY (parent_review_id)
    REFERENCES bookings.reviews (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.photos
    ADD FOREIGN KEY (product_id)
    REFERENCES bookings.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.parameters_values
    ADD FOREIGN KEY (product_id)
    REFERENCES bookings.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.parameters_values
    ADD FOREIGN KEY (parameter_id)
    REFERENCES bookings.parameters (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.parameters_categories
    ADD FOREIGN KEY (parameter_id)
    REFERENCES bookings.parameters (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS bookings.parameters_categories
    ADD FOREIGN KEY (category_id)
    REFERENCES bookings.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;